# The conda environment should generally be managed by raco setup.
# For manual use: 
#   conda env create --file environment.yml --prefix condaenv
#   conda env update --file environment.yml --prefix condaenv
name: pydrnlp
channels:
  - defaults
dependencies:
  - python=3.6.5
  - spacy=2.0.11
  - flask=0.12.2
  - pip=9.0.3
  - pip:
    - https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.0.0/en_core_web_sm-2.0.0.tar.gz#en_core_web_sm#egg=en-core-web-sm

