# The conda environment should generally be managed by raco setup.
# For manual use:
#   conda env create --file environment.yml --prefix condaenv
#   conda env update --file environment.yml --prefix condaenv
#   conda activate condaenv/
#   conda deactivate
name: pydrnlp
channels:
  - defaults
  - conda-forge # for spacy
dependencies:
  - python=3.7
  - spacy=2.1.8
  - srsly>=0.1.0
  - regex>=2019.03.12
  - scipy>=1.3.1 # for elbow
  - numpy>=1.16.4 # for elbow
  - pip>=19.0.3
  - pip:
    - https://github.com/explosion/spacy-models/releases/download/en_core_web_md-2.1.0/en_core_web_md-2.1.0.tar.gz#egg=en_core_web_md-2.1.0
    - https://github.com/explosion/spacy-models/releases/download/fr_core_news_sm-2.1.0/fr_core_news_sm-2.1.0.tar.gz#egg=fr_core_news_sm-2.1.0
    - https://github.com/explosion/spacy-models/releases/download/de_core_news_sm-2.1.0/de_core_news_sm-2.1.0.tar.gz#egg=de_core_news_sm-2.1.0
